theme = "monokai_pro"

[editor]
line-number = "relative"
mouse = false
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline


[editor.cursor-shape]
insert = "block"
normal = "block"
# select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
Z = { Z = ":wq!", Q = ":q!" }
